[package]
name = "rev-orp"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-files = "0.6.6"
actix-web= "4"
awc = "3.6.0"
chrono = "0.4.41"
serde = {version = "1.0.219", features = ["derive"]}
tokio = {version = "1.44.2", features=["full"]}
url = "2.5.4"
urlencoding = "2.1.3"
